#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
MERLIN_REPO=https://github.com/RMerl/asuswrt-merlin.ng.git
MERLIN_TAG=386.14_2
MERLIN_COMMIT=6a5df61aab6f3fa2dffc518994d42e4f2a27fb2b
TOOLCHAIN_REPO=https://github.com/RMerl/am-toolchains.git
TOOLCHAIN_COMMIT=d1af80e6b6686a4edc680386c09a8361453dd5c1

DEPS_DIR=${DEPS_DIR:-"$ROOT/_deps"}
SRC_DIR=${SRC_DIR:-"$DEPS_DIR/asuswrt-merlin.ng"}
TOOLCHAIN_DIR=${TOOLCHAIN_DIR:-"$DEPS_DIR/am-toolchains"}
OUT_DIR=${OUT_DIR:-"$ROOT/build-output"}
MAKE_JOBS=${MAKE_JOBS:-1}

PATCH=$ROOT/patches/0001-rt-ac68u-gretap-pptp-coexistence-nodf.patch
KCONFIG=$ROOT/build-support/kernel.config
SDKCONFIG=$ROOT/build-support/sdk.config
SYMVERS=$ROOT/build-support/Module.symvers
PATCHED_REL=release/src-rt-6.x.4708/linux/linux-2.6.36/net/ipv4/ip_gre.c
PATCH_APPLIED=0

cleanup() {
    if [ "$PATCH_APPLIED" -eq 1 ] && [ -d "$SRC_DIR/.git" ]; then
        git -C "$SRC_DIR" checkout -- "$PATCHED_REL" >/dev/null 2>&1 || true
    fi
}
trap cleanup EXIT HUP INT TERM

case "$MAKE_JOBS" in
    ''|*[!0-9]*) echo "ERROR: MAKE_JOBS must be a positive integer" >&2; exit 1 ;;
esac
[ "$MAKE_JOBS" -ge 1 ] || { echo "ERROR: MAKE_JOBS must be >= 1" >&2; exit 1; }

mkdir -p "$DEPS_DIR" "$OUT_DIR"

# Avoid surprise automatic repository maintenance while the pinned source
# and toolchain are being materialized. This matters on small build hosts.
export GIT_CONFIG_COUNT=1
export GIT_CONFIG_KEY_0=gc.auto
export GIT_CONFIG_VALUE_0=0

if [ ! -d "$SRC_DIR/.git" ]; then
    git clone --filter=blob:none --branch "$MERLIN_TAG" --single-branch "$MERLIN_REPO" "$SRC_DIR"
fi

if [ "$(git -C "$SRC_DIR" rev-parse HEAD)" != "$MERLIN_COMMIT" ]; then
    echo "ERROR: Merlin source is not at pinned commit $MERLIN_COMMIT" >&2
    exit 1
fi

if ! git -C "$SRC_DIR" diff --quiet --ignore-submodules --; then
    echo "ERROR: Merlin source tree is dirty. Use a clean checkout of the pinned commit." >&2
    exit 1
fi

if [ ! -d "$TOOLCHAIN_DIR/.git" ]; then
    git clone --filter=blob:none "$TOOLCHAIN_REPO" "$TOOLCHAIN_DIR"
fi

if ! git -C "$TOOLCHAIN_DIR" cat-file -e "$TOOLCHAIN_COMMIT^{commit}" 2>/dev/null; then
    git -C "$TOOLCHAIN_DIR" fetch origin "$TOOLCHAIN_COMMIT"
fi

git -C "$TOOLCHAIN_DIR" checkout --detach "$TOOLCHAIN_COMMIT" >/dev/null

SDKROOT=$SRC_DIR/release/src-rt-6.x.4708
KDIR=$SDKROOT/linux/linux-2.6.36
TOOLCHAIN_ROOT=$TOOLCHAIN_DIR/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3
CROSS=$TOOLCHAIN_ROOT/bin/arm-brcm-linux-uclibcgnueabi-
export LD_LIBRARY_PATH="$TOOLCHAIN_ROOT/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

if [ ! -x "${CROSS}gcc" ]; then
    echo "ERROR: expected cross compiler not found: ${CROSS}gcc" >&2
    exit 1
fi

# The Broadcom kernel Makefile includes ../../.config. This SDK-level config
# is generated by the firmware build and is therefore carried explicitly.
cp "$SDKCONFIG" "$SDKROOT/.config"
cp "$KCONFIG" "$KDIR/.config"

git -C "$SRC_DIR" apply --check "$PATCH"
git -C "$SRC_DIR" apply "$PATCH"
PATCH_APPLIED=1

make -j"$MAKE_JOBS" -C "$KDIR" ARCH=arm CROSS_COMPILE="$CROSS" oldconfig </dev/null
make -j"$MAKE_JOBS" -C "$KDIR" ARCH=arm CROSS_COMPILE="$CROSS" prepare modules_prepare
make -j"$MAKE_JOBS" -C "$KDIR" ARCH=arm CROSS_COMPILE="$CROSS" M=net/ipv4 clean
cp "$SYMVERS" "$KDIR/Module.symvers"

# Building M=net/ipv4 is intentional. On this old Kbuild, directly requesting
# net/ipv4/ip_gre.ko bypasses the module-wide MODPOST step and produces an
# empty __versions section. The M= build produces the correct modversion CRCs.
make -j"$MAKE_JOBS" -C "$KDIR" ARCH=arm CROSS_COMPILE="$CROSS" M=net/ipv4 modules

cp "$KDIR/net/ipv4/ip_gre.ko" "$OUT_DIR/ip_gre_asus_pptpfix_nodf.ko"

# DWARF embeds the absolute source path and GNU build-id consequently varies
# across build directories. Neither is required at runtime. Removing both
# makes the release artifact reproducible while retaining module symbols,
# relocations, modinfo and CONFIG_MODVERSIONS data.
"${CROSS}objcopy" --strip-debug --remove-section=.note.gnu.build-id \
    "$OUT_DIR/ip_gre_asus_pptpfix_nodf.ko"

printf 'Built: %s\n' "$OUT_DIR/ip_gre_asus_pptpfix_nodf.ko"
sha256sum "$OUT_DIR/ip_gre_asus_pptpfix_nodf.ko"
